services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PIE_VERSION: ${PIE_VERSION:-1.3.8}
        CORE_VERSION: ${CORE_VERSION:-0.0.3}
        GATEWAY_VERSION: ${GATEWAY_VERSION:-0.0.2}
        DISCOVERY_VERSION: ${DISCOVERY_VERSION:-0.0.3}
        QUEUE_VERSION: ${QUEUE_VERSION:-0.0.1}
        METRICS_VERSION: ${METRICS_VERSION:-0.0.1}
        CONFIG_VERSION: ${CONFIG_VERSION:-0.0.1}
        EVENTBUS_VERSION: ${EVENTBUS_VERSION:-0.0.1}
        PERSISTENCE_VERSION: ${PERSISTENCE_VERSION:-0.0.1}
        REQUIRED_EXTENSIONS: ${REQUIRED_EXTENSIONS:-}
    container_name: kislayphp-skeleton
    env_file:
      - .env
    environment:
      APP_NAME: ${APP_NAME:-KislayApp}
      APP_ENV: ${APP_ENV:-production}
      HTTP_PORT: ${HTTP_PORT:-9000}
      GATEWAY_PORT: ${GATEWAY_PORT:-9008}
      DISCOVERY_PORT: ${DISCOVERY_PORT:-9090}
      DB_PATH: ${DB_PATH:-/app/storage/database.sqlite}
    ports:
      - "${HTTP_PORT:-9000}:${HTTP_PORT:-9000}"
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
